version: '3.8'

services:
  usermanagement.api:
    image: usermanagement.api
    build:
      context: .
      dockerfile: UserManagement.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
